import { supabase, isSupabaseConfigured } from "../lib/supabaseClient";
import { getDinosaurImage } from "../utils/dinosaurImage";

function entry({
  id,
  name,
  scientific_name,
  period,
  age,
  discovery_year,
  country,
  location_province,
  latitude,
  longitude,
  fossil_parts,
  description,
  fun_fact,
  image_url = null,
}) {
  return {
    id,
    name,
    scientific_name,
    period,
    age,
    discovery_year,
    country,
    location_province,
    latitude,
    longitude,
    fossil_parts,
    description,
    fun_fact,
    image_url,
  };
}

const FALLBACK_FOSSIL_LOCATIONS = [
  entry({
    id: "fallback-coelophysis-ghost-ranch",
    name: "Coelophysis",
    scientific_name: "Coelophysis bauri",
    period: "Kỷ Tam Điệp muộn",
    age: "Khoảng 203–196 triệu năm trước",
    discovery_year: "1881",
    country: "Hoa Kỳ",
    location_province: "New Mexico",
    latitude: 36.268,
    longitude: -104.028,
    fossil_parts: "Bộ xương gần hoàn chỉnh, xương chi và hộp sọ.",
    description: "Theropod sớm nổi tiếng từ quần thể hóa thạch Ghost Ranch.",
    fun_fact: "Ghost Ranch là một trong những địa điểm Coelophysis nổi tiếng nhất thế giới.",
  }),
  entry({
    id: "fallback-eoraptor-ischigualasto",
    name: "Eoraptor",
    scientific_name: "Eoraptor lunensis",
    period: "Kỷ Tam Điệp muộn",
    age: "Khoảng 231 triệu năm trước",
    discovery_year: "1991",
    country: "Argentina",
    location_province: "San Juan",
    latitude: -30.206,
    longitude: -68.99,
    fossil_parts: "Hộp sọ, đốt sống và xương chi.",
    description: "Một trong những khủng long cổ nhất, đến từ hệ tầng Ischigualasto.",
    fun_fact: "Ischigualasto còn được gọi là Valley of the Moon.",
  }),
  entry({
    id: "fallback-plateosaurus-trossingen",
    name: "Plateosaurus",
    scientific_name: "Plateosaurus engelhardti",
    period: "Kỷ Tam Điệp muộn",
    age: "Khoảng 214–204 triệu năm trước",
    discovery_year: "1834",
    country: "Đức",
    location_province: "Trossingen",
    latitude: 48.082,
    longitude: 8.644,
    fossil_parts: "Nhiều bộ xương bán hoàn chỉnh.",
    description: "Prosauropod lớn tiêu biểu trong các tầng đá Tam Điệp cuối của châu Âu.",
    fun_fact: "Trossingen là mỏ hóa thạch Plateosaurus kinh điển của châu Âu.",
  }),
  entry({
    id: "fallback-liliensternus-thuringia",
    name: "Liliensternus",
    scientific_name: "Liliensternus liliensterni",
    period: "Kỷ Tam Điệp muộn",
    age: "Khoảng 210 triệu năm trước",
    discovery_year: "1934",
    country: "Đức",
    location_province: "Thuringia",
    latitude: 50.873,
    longitude: 11.383,
    fossil_parts: "Xương chậu, chi sau và đốt sống.",
    description: "Theropod sớm của châu Âu với kích thước lớn hơn nhiều họ hàng Tam Điệp.",
    fun_fact: "Loài này được mô tả từ các hóa thạch tìm thấy ở miền trung nước Đức.",
  }),
  entry({
    id: "fallback-massospondylus-eastern-cape",
    name: "Massospondylus",
    scientific_name: "Massospondylus carinatus",
    period: "Kỷ Jura sớm",
    age: "Khoảng 200–183 triệu năm trước",
    discovery_year: "1854",
    country: "Nam Phi",
    location_province: "Eastern Cape",
    latitude: -31.558,
    longitude: 25.568,
    fossil_parts: "Sọ, chi sau, xương vai và tổ trứng.",
    description: "Prosauropod nổi tiếng từ miền nam châu Phi, thuộc giai đoạn đầu Jura.",
    fun_fact: "Các tổ trứng Massospondylus giúp hé lộ tập tính sinh sản khủng long sớm.",
  }),
  entry({
    id: "fallback-camarasaurus-colorado",
    name: "Camarasaurus",
    scientific_name: "Camarasaurus",
    period: "Kỷ Jura muộn",
    age: "Khoảng 155–145 triệu năm trước",
    discovery_year: "1877",
    country: "Hoa Kỳ",
    location_province: "Colorado",
    latitude: 39.113,
    longitude: -108.536,
    fossil_parts: "Đốt sống, xương sườn, chi trước và sau.",
    description: "Sauropod phổ biến trong hệ tầng Morrison của Bắc Mỹ.",
    fun_fact: "Morrison Formation là kho tư liệu hóa thạch lớn của Kỷ Jura Bắc Mỹ.",
  }),
  entry({
    id: "fallback-stegosaurus-colorado",
    name: "Stegosaurus",
    scientific_name: "Stegosaurus stenops",
    period: "Kỷ Jura muộn",
    age: "Khoảng 155–150 triệu năm trước",
    discovery_year: "1877",
    country: "Hoa Kỳ",
    location_province: "Colorado",
    latitude: 38.94,
    longitude: -105.157,
    fossil_parts: "Tấm lưng, gai đuôi và xương chi.",
    description: "Loài ăn cỏ nổi bật với các tấm xương dọc lưng và gai đuôi.",
    fun_fact: "Nhiều mẫu Stegosaurus trứ danh đến từ vùng Morrison của Colorado.",
  }),
  entry({
    id: "fallback-allosaurus-utah",
    name: "Allosaurus",
    scientific_name: "Allosaurus fragilis",
    period: "Kỷ Jura muộn",
    age: "Khoảng 155–145 triệu năm trước",
    discovery_year: "1877",
    country: "Hoa Kỳ",
    location_province: "Utah",
    latitude: 39.321,
    longitude: -110.689,
    fossil_parts: "Hộp sọ, răng và xương chi.",
    description: "Động vật săn mồi lớn thống trị nhiều hệ sinh thái Jura Bắc Mỹ.",
    fun_fact: "Cleveland-Lloyd Dinosaur Quarry có số lượng Allosaurus rất lớn.",
  }),
  entry({
    id: "fallback-diplodocus-utah",
    name: "Diplodocus",
    scientific_name: "Diplodocus carnegii",
    period: "Kỷ Jura muộn",
    age: "Khoảng 154–152 triệu năm trước",
    discovery_year: "1878",
    country: "Hoa Kỳ",
    location_province: "Utah",
    latitude: 39.247,
    longitude: -109.723,
    fossil_parts: "Đuôi dài, đốt sống cổ và chi sau.",
    description: "Một trong những sauropod dễ nhận biết nhất với đuôi roi rất dài.",
    fun_fact: "Diplodocus từng là biểu tượng ngoại giao bảo tàng đầu thế kỷ 20.",
  }),
  entry({
    id: "fallback-brachiosaurus-colorado",
    name: "Brachiosaurus",
    scientific_name: "Brachiosaurus altithorax",
    period: "Kỷ Jura muộn",
    age: "Khoảng 154–150 triệu năm trước",
    discovery_year: "1900",
    country: "Hoa Kỳ",
    location_province: "Colorado",
    latitude: 39.55,
    longitude: -107.324,
    fossil_parts: "Chi trước rất dài, đốt sống và xương vai.",
    description: "Sauropod khổng lồ nổi bật với tư thế cổ cao và chi trước dài.",
    fun_fact: "Tên Brachiosaurus nghĩa là “thằn lằn tay” vì chi trước dài bất thường.",
  }),
  entry({
    id: "fallback-archaeopteryx-solnhofen",
    name: "Archaeopteryx",
    scientific_name: "Archaeopteryx lithographica",
    period: "Kỷ Jura muộn",
    age: "Khoảng 150 triệu năm trước",
    discovery_year: "1861",
    country: "Đức",
    location_province: "Bavaria",
    latitude: 48.898,
    longitude: 10.998,
    fossil_parts: "Bộ xương kèm dấu lông vũ.",
    description: "Một trong những hóa thạch quan trọng nhất cho quá trình chuyển tiếp sang chim.",
    fun_fact: "Các phiến đá vôi Solnhofen bảo tồn chi tiết lông vũ rất hiếm.",
  }),
  entry({
    id: "fallback-iguanodon-bernissart",
    name: "Iguanodon",
    scientific_name: "Iguanodon bernissartensis",
    period: "Kỷ Phấn Trắng sớm",
    age: "Khoảng 126–122 triệu năm trước",
    discovery_year: "1878",
    country: "Bỉ",
    location_province: "Bernissart",
    latitude: 50.475,
    longitude: 3.648,
    fossil_parts: "Nhiều bộ xương gần hoàn chỉnh.",
    description: "Một trong những ornithopod đầu tiên được phát hiện với số lượng lớn.",
    fun_fact: "Mỏ than Bernissart từng cho ra hàng chục bộ xương Iguanodon.",
  }),
  entry({
    id: "fallback-spinosaurus-morocco",
    name: "Spinosaurus",
    scientific_name: "Spinosaurus aegyptiacus",
    period: "Kỷ Phấn Trắng giữa",
    age: "Khoảng 99–93 triệu năm trước",
    discovery_year: "1912",
    country: "Ma-rốc",
    location_province: "Kem Kem",
    latitude: 31.835,
    longitude: -4.55,
    fossil_parts: "Mõm dài, răng hình nón, gai sống lưng.",
    description: "Động vật săn mồi bán thủy sinh nổi tiếng từ tầng Kem Kem.",
    fun_fact: "Spinosaurus hiện được xem là một trong những theropod đặc dị nhất từng biết.",
  }),
  entry({
    id: "fallback-carcharodontosaurus-morocco",
    name: "Carcharodontosaurus",
    scientific_name: "Carcharodontosaurus saharicus",
    period: "Kỷ Phấn Trắng giữa",
    age: "Khoảng 100–94 triệu năm trước",
    discovery_year: "1925",
    country: "Ma-rốc",
    location_province: "Sahara",
    latitude: 31.925,
    longitude: -4.211,
    fossil_parts: "Sọ, răng lớn dạng dao và xương hàm.",
    description: "Theropod khổng lồ của Bắc Phi, cùng môi trường với Spinosaurus.",
    fun_fact: "Tên loài nghĩa là “thằn lằn răng cá mập”.",
  }),
  entry({
    id: "fallback-ouranosaurus-niger",
    name: "Ouranosaurus",
    scientific_name: "Ouranosaurus nigeriensis",
    period: "Kỷ Phấn Trắng sớm",
    age: "Khoảng 125–112 triệu năm trước",
    discovery_year: "1966",
    country: "Niger",
    location_province: "Gadoufaoua",
    latitude: 17.789,
    longitude: 9.725,
    fossil_parts: "Đốt sống lưng cao, chi và xương chậu.",
    description: "Ornithopod nổi bật với phần sống lưng cao tạo thành “cánh buồm”.",
    fun_fact: "Gadoufaoua là một trong những khu hóa thạch nổi tiếng nhất Sahara.",
  }),
  entry({
    id: "fallback-giraffatitan-tanzania",
    name: "Giraffatitan",
    scientific_name: "Giraffatitan brancai",
    period: "Kỷ Jura muộn",
    age: "Khoảng 154–150 triệu năm trước",
    discovery_year: "1906",
    country: "Tanzania",
    location_province: "Lindi",
    latitude: -10.044,
    longitude: 39.613,
    fossil_parts: "Chi trước, cổ, đốt sống và xương vai.",
    description: "Sauropod châu Phi rất lớn, từng được gộp với Brachiosaurus.",
    fun_fact: "Khu Tendaguru ở Tanzania là mỏ hóa thạch Jura nổi tiếng toàn cầu.",
  }),
  entry({
    id: "fallback-mamenchisaurus-sichuan",
    name: "Mamenchisaurus",
    scientific_name: "Mamenchisaurus hochuanensis",
    period: "Kỷ Jura muộn",
    age: "Khoảng 160–145 triệu năm trước",
    discovery_year: "1952",
    country: "Trung Quốc",
    location_province: "Sichuan",
    latitude: 29.701,
    longitude: 105.897,
    fossil_parts: "Cổ dài, đốt sống và chi.",
    description: "Sauropod châu Á nổi tiếng với chiếc cổ cực dài.",
    fun_fact: "Một số loài Mamenchisaurus có cổ dài hơn 10 mét.",
  }),
  entry({
    id: "fallback-shunosaurus-sichuan",
    name: "Shunosaurus",
    scientific_name: "Shunosaurus lii",
    period: "Kỷ Jura giữa",
    age: "Khoảng 170 triệu năm trước",
    discovery_year: "1977",
    country: "Trung Quốc",
    location_province: "Sichuan",
    latitude: 29.436,
    longitude: 104.801,
    fossil_parts: "Đuôi chùy, cổ và chi.",
    description: "Sauropod đặc biệt vì có chùy ở đuôi hiếm gặp.",
    fun_fact: "Dashanpu Fossil Site là một kho hóa thạch khủng long quan trọng của Trung Quốc.",
  }),
  entry({
    id: "fallback-psittacosaurus-liaoning",
    name: "Psittacosaurus",
    scientific_name: "Psittacosaurus mongoliensis",
    period: "Kỷ Phấn Trắng sớm",
    age: "Khoảng 125–100 triệu năm trước",
    discovery_year: "1923",
    country: "Trung Quốc",
    location_province: "Liaoning",
    latitude: 41.576,
    longitude: 120.437,
    fossil_parts: "Sọ, chi và các mẫu bảo tồn mô mềm hiếm.",
    description: "Ceratopsian sớm, nhỏ, thường được tìm thấy ở Đông Á.",
    fun_fact: "Một số mẫu Psittacosaurus cho thấy dấu vết mô mềm và sắc tố.",
  }),
  entry({
    id: "fallback-velociraptor-mongolia",
    name: "Velociraptor",
    scientific_name: "Velociraptor mongoliensis",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 75–71 triệu năm trước",
    discovery_year: "1924",
    country: "Mông Cổ",
    location_province: "Ömnögovi",
    latitude: 43.532,
    longitude: 104.167,
    fossil_parts: "Sọ, móng vuốt và bộ xương chi sau.",
    description: "Dromaeosaurid nhỏ nhưng cực kỳ nổi tiếng từ sa mạc Gobi.",
    fun_fact: "Mẫu “Fighting Dinosaurs” với Protoceratops là một hóa thạch biểu tượng.",
    image_url: "/images/dino_velociraptor.png",
  }),
  entry({
    id: "fallback-protoceratops-mongolia",
    name: "Protoceratops",
    scientific_name: "Protoceratops andrewsi",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 75–71 triệu năm trước",
    discovery_year: "1923",
    country: "Mông Cổ",
    location_province: "Ömnögovi",
    latitude: 43.638,
    longitude: 104.18,
    fossil_parts: "Sọ, cổ và xương thân.",
    description: "Ceratopsian nhỏ, cực kỳ phổ biến trong các trầm tích sa mạc Gobi.",
    fun_fact: "Nhiều tổ trứng cổ từng bị nhầm là trứng Protoceratops.",
  }),
  entry({
    id: "fallback-tarbosaurus-mongolia",
    name: "Tarbosaurus",
    scientific_name: "Tarbosaurus bataar",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 70 triệu năm trước",
    discovery_year: "1946",
    country: "Mông Cổ",
    location_province: "Nemegt",
    latitude: 43.732,
    longitude: 101.899,
    fossil_parts: "Sọ lớn, răng và xương chi.",
    description: "Họ hàng châu Á rất gần với Tyrannosaurus rex.",
    fun_fact: "Hệ tầng Nemegt là một trong những môi trường cuối Phấn Trắng nổi tiếng nhất châu Á.",
  }),
  entry({
    id: "fallback-oviraptor-mongolia",
    name: "Oviraptor",
    scientific_name: "Oviraptor philoceratops",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 75 triệu năm trước",
    discovery_year: "1924",
    country: "Mông Cổ",
    location_province: "Bayanzag",
    latitude: 44.072,
    longitude: 103.703,
    fossil_parts: "Sọ, xương chi và mẫu ngồi trên tổ trứng.",
    description: "Theropod có mỏ, nổi tiếng nhờ các hóa thạch liên quan đến tổ trứng.",
    fun_fact: "Oviraptor từng bị hiểu nhầm là kẻ cướp trứng trước khi có bằng chứng mới.",
  }),
  entry({
    id: "fallback-tyrannosaurus-montana",
    name: "Tyrannosaurus",
    scientific_name: "Tyrannosaurus rex",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 68–66 triệu năm trước",
    discovery_year: "1902",
    country: "Hoa Kỳ",
    location_province: "Montana",
    latitude: 47.058,
    longitude: -106.617,
    fossil_parts: "Hộp sọ, răng, xương chậu và nhiều chi.",
    description: "Loài săn mồi đỉnh cao cuối Phấn Trắng của Bắc Mỹ.",
    fun_fact: "Hell Creek là nơi khai quật nhiều mẫu T. rex trứ danh.",
    image_url: "/images/Tyrannosaurus_rex.png",
  }),
  entry({
    id: "fallback-triceratops-wyoming",
    name: "Triceratops",
    scientific_name: "Triceratops horridus",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 68–66 triệu năm trước",
    discovery_year: "1887",
    country: "Hoa Kỳ",
    location_province: "Wyoming",
    latitude: 43.059,
    longitude: -105.504,
    fossil_parts: "Sọ, sừng mặt và nhiều đốt sống.",
    description: "Ceratopsian tiêu biểu của Bắc Mỹ cuối Phấn Trắng.",
    fun_fact: "Các hộp sọ Triceratops là một trong những hóa thạch dễ nhận biết nhất.",
    image_url: "/images/Triceratops.png",
  }),
  entry({
    id: "fallback-edmontosaurus-south-dakota",
    name: "Edmontosaurus",
    scientific_name: "Edmontosaurus annectens",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 73–66 triệu năm trước",
    discovery_year: "1892",
    country: "Hoa Kỳ",
    location_province: "South Dakota",
    latitude: 44.373,
    longitude: -102.952,
    fossil_parts: "Mỏ vịt, đốt sống và nhiều xương thân.",
    description: "Hadrosaur rất phổ biến trong các đồng bằng ven biển cuối Phấn Trắng.",
    fun_fact: "Một số mẫu Edmontosaurus còn bảo tồn ấn tượng da hóa thạch.",
  }),
  entry({
    id: "fallback-ankylosaurus-montana",
    name: "Ankylosaurus",
    scientific_name: "Ankylosaurus magniventris",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 68–66 triệu năm trước",
    discovery_year: "1906",
    country: "Hoa Kỳ",
    location_province: "Montana",
    latitude: 47.233,
    longitude: -104.824,
    fossil_parts: "Giáp lưng, đuôi chùy và hộp sọ.",
    description: "Ankylosaurid khổng lồ với cơ thể bọc giáp và đuôi chùy nổi tiếng.",
    fun_fact: "Ankylosaurus là một trong những “xe tăng sống” nổi tiếng nhất lịch sử sự sống.",
  }),
  entry({
    id: "fallback-pachycephalosaurus-south-dakota",
    name: "Pachycephalosaurus",
    scientific_name: "Pachycephalosaurus wyomingensis",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 70–66 triệu năm trước",
    discovery_year: "1931",
    country: "Hoa Kỳ",
    location_province: "South Dakota",
    latitude: 44.704,
    longitude: -103.864,
    fossil_parts: "Mái sọ dày và xương đầu.",
    description: "Khủng long đầu dày nổi tiếng của hệ tầng Hell Creek.",
    fun_fact: "Chiếc hộp sọ dày bất thường khiến nó trở thành biểu tượng rất dễ nhớ.",
  }),
  entry({
    id: "fallback-styracosaurus-alberta",
    name: "Styracosaurus",
    scientific_name: "Styracosaurus albertensis",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 75–76 triệu năm trước",
    discovery_year: "1913",
    country: "Canada",
    location_province: "Alberta",
    latitude: 51.383,
    longitude: -112.527,
    fossil_parts: "Sọ, diềm cổ và sừng đặc trưng.",
    description: "Ceratopsian nổi bật với diềm cổ gai dài từ Alberta.",
    fun_fact: "Alberta là một trong những điểm nóng hóa thạch khủng long nổi tiếng nhất thế giới.",
    image_url: "/images/Styracosaurus%20.png",
  }),
  entry({
    id: "fallback-pachyrhinosaurus-alberta",
    name: "Pachyrhinosaurus",
    scientific_name: "Pachyrhinosaurus lakustai",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 73–69 triệu năm trước",
    discovery_year: "1946",
    country: "Canada",
    location_province: "Alberta",
    latitude: 56.123,
    longitude: -117.462,
    fossil_parts: "Sọ với gờ mũi dày, xương cổ.",
    description: "Ceratopsian có mũi to dày thay cho sừng mũi nhọn.",
    fun_fact: "Các mỏ xương Pachyrhinosaurus cho thấy chúng có thể di chuyển theo đàn lớn.",
  }),
  entry({
    id: "fallback-argentinosaurus-patagonia",
    name: "Argentinosaurus",
    scientific_name: "Argentinosaurus huinculensis",
    period: "Kỷ Phấn Trắng giữa",
    age: "Khoảng 96–92 triệu năm trước",
    discovery_year: "1987",
    country: "Argentina",
    location_province: "Neuquén",
    latitude: -38.949,
    longitude: -68.058,
    fossil_parts: "Đốt sống lớn, xương chày và xương sườn.",
    description: "Một trong những động vật trên cạn lớn nhất từng tồn tại.",
    fun_fact: "Các hóa thạch được phát hiện ở Patagonia đã định hình lại ước tính kích thước sauropod.",
  }),
  entry({
    id: "fallback-carnotaurus-chubut",
    name: "Carnotaurus",
    scientific_name: "Carnotaurus sastrei",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 72–69 triệu năm trước",
    discovery_year: "1984",
    country: "Argentina",
    location_province: "Chubut",
    latitude: -44.142,
    longitude: -69.503,
    fossil_parts: "Sọ có sừng, chi sau và dấu da bảo tồn tốt.",
    description: "Abelisaurid nhanh và rất đặc trưng với cặp sừng trên hốc mắt.",
    fun_fact: "Carnotaurus là một trong số ít theropod lớn có dấu da khá rõ.",
  }),
  entry({
    id: "fallback-amargasaurus-neuquen",
    name: "Amargasaurus",
    scientific_name: "Amargasaurus cazaui",
    period: "Kỷ Phấn Trắng sớm",
    age: "Khoảng 129–122 triệu năm trước",
    discovery_year: "1984",
    country: "Argentina",
    location_province: "Neuquén",
    latitude: -39.95,
    longitude: -70.043,
    fossil_parts: "Cổ gai dài, lưng và đốt sống.",
    description: "Sauropod nhỏ hơn nhưng cực kỳ nổi bật với hàng gai ở cổ.",
    fun_fact: "Các gai cổ của Amargasaurus là một trong những hình thái kỳ lạ nhất ở sauropod.",
  }),
  entry({
    id: "fallback-kentrosaurus-tanzania",
    name: "Kentrosaurus",
    scientific_name: "Kentrosaurus aethiopicus",
    period: "Kỷ Jura muộn",
    age: "Khoảng 152–150 triệu năm trước",
    discovery_year: "1909",
    country: "Tanzania",
    location_province: "Tendaguru",
    latitude: -10.16,
    longitude: 39.62,
    fossil_parts: "Gai đuôi, tấm lưng và xương chi.",
    description: "Stegosaur châu Phi nhỏ hơn Stegosaurus nhưng phòng thủ mạnh mẽ với nhiều gai.",
    fun_fact: "Tendaguru cũng là nơi cho ra nhiều hóa thạch sauropod khổng lồ.",
  }),
  entry({
    id: "fallback-maiasaura-montana",
    name: "Maiasaura",
    scientific_name: "Maiasaura peeblesorum",
    period: "Kỷ Phấn Trắng muộn",
    age: "Khoảng 76–74 triệu năm trước",
    discovery_year: "1978",
    country: "Hoa Kỳ",
    location_province: "Montana",
    latitude: 47.784,
    longitude: -109.188,
    fossil_parts: "Ổ trứng, xương non và xương trưởng thành.",
    description: "Hadrosaur nổi tiếng với bằng chứng chăm sóc con non trong tổ.",
    fun_fact: "Tên Maiasaura có nghĩa là “thằn lằn mẹ tốt”.",
  }),
];

function toNumber(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function normalizeFossilLocation(row) {
  const latitude = toNumber(row.latitude ?? row.lat);
  const longitude = toNumber(row.longitude ?? row.lng ?? row.lon);

  if (latitude == null || longitude == null) {
    return null;
  }

  const scientificName =
    row.scientific_name ||
    row.scientificName ||
    row.binomial_name ||
    row.name ||
    row.slug ||
    "";
  const displayName =
    row.common_name ||
    row.common_name_vi ||
    row.common_name_en ||
    row.display_name ||
    row.name ||
    scientificName ||
    "Hóa thạch";

  return {
    ...row,
    id: row.id ?? `${scientificName}-${latitude}-${longitude}`,
    name: displayName,
    scientific_name: scientificName || null,
    country: row.country || row.discovery_country || null,
    location_province:
      row.location_province || row.province || row.state || row.discovery_location || null,
    latitude,
    longitude,
    image_url: row.image_url || getDinosaurImage(row) || null,
    period: row.period || row.era || row.period_name || null,
    age: row.age || row.age_mya || null,
    discovery_year: row.discovery_year || row.year_discovered || null,
    fossil_parts: row.fossil_parts || row.fossil_type || row.specimen_parts || null,
    description: row.description || row.description_vi || row.description_en || null,
    fun_fact: row.fun_fact || row.fact || null,
  };
}

function getFallbackLocations() {
  return FALLBACK_FOSSIL_LOCATIONS.map(normalizeFossilLocation).filter(Boolean);
}

export async function getFossilLocations() {
  if (!isSupabaseConfigured) {
    return { data: getFallbackLocations(), source: "fallback:no-env" };
  }

  const { data, error } = await supabase
    .from("fossil_locations")
    .select("*")
    .order("id", { ascending: true });

  if (error) {
    console.error("Error fetching fossil_locations:", error);
    return { data: getFallbackLocations(), source: "fallback:error" };
  }

  const normalized = (data || []).map(normalizeFossilLocation).filter(Boolean);

  if (normalized.length) {
    return { data: normalized, source: "supabase" };
  }

  return { data: getFallbackLocations(), source: "fallback:empty" };
}
